#!/bin/bash

# USAGE: back [number] (default: 1)
# Traverses up n directories;
# Example: back is equivalent to cd ..	back 2 is equivalent to cd ../..
function backfunc(){
	NDIR=0

	# Do nothing if argument is 0 or negative
	if [ $# -eq 0 ]; then
		let NDIR=1
	elif [ "$#" -gt "1" ]; then
		echo "USAGE: back [number] (default: 1)"
		return
	else
		NDIR=$1
	fi

	cd ..
	while [ "$NDIR" -gt "1" ]; do
		cd ..
		let NDIR=NDIR-1
	done
}
alias back='backfunc'
