#!/bin/bash

# Combines cd and mv to cd into the directory you moved something into
# Not thoroughly tested; need to add -r option for directories

function cdmv(){
	FILE=$1
	DIR=$2
	mv $FILE $DIR
	cd $DIR
}
alias cv='cdmv'
