#! /bin/sh

# Shortcut for SSH connection to the UCLA SEASNet server.
# Usage: sshseas [server]

SERVER=$1

if [ -z "$SERVER" ] # server number to connect to
then
	SERVER=6 # default is 7
fi

sshpass -p "$SEAS" ssh -Y "malahieu@lnxsrv0$SERVER.seas.ucla.edu"
