#! /bin/sh

# Usage: sshseas [server]
# Shortcut for SSH connection to the UCLA SEASNet server.

SERVER=$1

if [ -z "$SERVER" ] # server number to connect to
then
	SERVER=9 # default is 9
fi

sshpass -p "$SEAS" ssh -Y "$SEAS_UN@lnxsrv0$SERVER.seas.ucla.edu"
